apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-apiserver-pdb
  namespace: openshift-kube-apiserver
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: openshift-kube-apiserver
      apiserver: "true"
