apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: etcd-object-counts
  namespace: openshift-kube-apiserver
spec:
  groups:
    - name: etcd-object-counts
      rules:
        - alert: etcdHighCRDObjectCounts
          annotations:
            summary: etcd recorded {{ $value }} {{ $labels.resource }} objects.
            description: |
              etcd recorded {{ $value }} {{ $labels.resource }} objects. A high number of CRD objects is known to have caused stability issues in the API server and etcd storage stack. Information on diagnosis and mitigation steps can be found in the runbook.
            runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/etcdHighObjectCounts.md
          expr: |
            cluster:usage:resources:sum{resource!~".*k8s.io|^[^.]+"} > 200
          for: 10m
          labels:
            severity: warning
        - alert: etcdHighK8sObjectCounts
          annotations:
            summary: etcd recorded {{ $value }} {{ $labels.resource }} objects.
            description: |
              etcd recorded {{ $value }} {{ $labels.resource }} objects. A high number of objects is known to have caused stability issues in the API server and etcd storage stack. Information on diagnosis and mitigation steps can be found in the runbook.
            runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/etcdHighObjectCounts.md
          expr: |
            cluster:usage:resources:sum{resource=~".*k8s.io|^[^.]+"} > 700
          for: 10m
          labels:
            severity: warning
        - alert: KubeAPIIncreasingListResponseSize
          annotations:
            summary: The LIST response size among the {{ if $labels.group }}{{ $labels.group }}/{{ end }}{{ $labels.version }}/{{ $labels.resource }} objects has been increasing.
            description: |
              The LIST response size among the {{ if $labels.group }}{{ $labels.group }}/{{ end }}{{ $labels.version }}/{{ $labels.resource }} objects has been increasing at an average rate of {{ printf "%.2f" "$value" }} bytes/second in the past 10 minutes. If this rate continues to increase, it can caused stability issues in the API server. Information on diagnosis and mitigation steps can be found in the runbook.
            runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/kubeAPIIncreasingListResponseSize.md
          expr: |
            sum by(group,version,resource)(rate(apiserver_response_sizes_sum{verb="LIST"}[10m])) > 100000
          for: 10m
          labels:
            severity: warning
