{
 "title": "API Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "apiserver",
    "label": "apiserver",
    "query": "label_values(apiserver_request_total, apiserver)"
   },
   { "name": "period", "label": "interval", "query": "1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "API Request Duration by Verb - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(resource_verb:apiserver_request_duration_seconds_bucket:rate:$period{apiserver=\"$apiserver\"}) by (verb, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "etcd Request Duration - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, operation:etcd_request_duration_seconds_bucket:rate$period)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Request Duration by Resource and Verb - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, histogram_quantile(0.99, resource_verb:apiserver_request_duration_seconds_bucket:rate:$period{apiserver=\"$apiserver\"}))",
     "legendFormat": "{{resource}}-{{verb}}"
    }
   ]
  },
  {
   "title": "Request Rate by Resource and Verb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, resource_verb:apiserver_request_total:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{resource}}-{{verb}}"
    }
   ]
  },
  {
   "title": "Request Duration by Read vs Write - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, list:apiserver_request_duration_seconds_bucket:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "read"
    },
    {
     "expr": "histogram_quantile(0.99, write:apiserver_request_duration_seconds_bucket:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Request Rate by Read vs Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "read:apiserver_request_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "read"
    },
    {
     "expr": "write:apiserver_request_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Requests Dropped Rate",
   "type": "graph",
   "description": "Number of requests dropped with 'Try again later' response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_kind:apiserver_dropped_requests_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  {
   "title": "Requests Terminated Rate",
   "type": "graph",
   "description": "Number of requests which apiserver terminated in self-defense.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "component_resource:apiserver_request_terminations_total:rate:$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{component}}-{{resource}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "code:apiserver_request_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Rate by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:apiserver_request_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Long Running Requests by Resource",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, resource:apiserver_longrunning_requests:sum{apiserver=\"$apiserver\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Long Running Requests by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:apiserver_longrunning_requests:sum{apiserver=\"$apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests in Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance_request_kind:apiserver_current_inflight_requests:sum{apiserver=\"$apiserver\"}",
     "legendFormat": "{{instance}}:{{request_kind}}"
    }
   ]
  },
  {
   "title": "Response Bytes per Second by Instance",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:apiserver_response_sizes_sum:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Bytes per Second by Resource and Verb",
   "type": "graph",
   "description": "Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, resource_verb:apiserver_response_sizes_sum:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Requests Rejected",
   "type": "graph",
   "description": "Number of requests rejected by API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flow_schema_priority_level_reason:apiserver_flowcontrol_rejected_requests_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{flow_schema}}:{{priority_level}}:{{reason}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Wait Duration - 99th Percentile",
   "type": "graph",
   "description": "Length of time a request spent waiting in its queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, flow_schema_priority_level:apiserver_flowcontrol_request_wait_duration_seconds_bucket:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Queue Length",
   "type": "graph",
   "description": "Length of queue in the API Priority and Fairness system, as seen by each request after it is enqueued",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, flow_schema_priority_reason:apiserver_flowcontrol_request_queue_length_after_enqueue_bucket:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Dispatch Rate",
   "type": "graph",
   "description": "Number of requests released by API Priority and Fairness system for service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flow_schema_priority_level:apiserver_flowcontrol_request_execution_seconds_bucket:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Request Execution Duration - 99th Percentile",
   "type": "graph",
   "description": "Duration of request execution in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, flow_schema_priority_level_le:apiserver_flowcontrol_request_execution_seconds_bucket:rate$period{apiserver=\"$apiserver\"}) ",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Currently Executing Requests",
   "type": "graph",
   "description": "Number of requests currently executing in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flow_schema_priority_level:apiserver_flowcontrol_current_executing_requests:sum{apiserver=\"$apiserver\"}",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Concurrency Limit by Priority Level",
   "type": "graph",
   "description": "Shared concurrency limit in the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "priority_level:apiserver_flowcontrol_request_concurrency_limit:sum{apiserver=\"$apiserver\"}",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Priority & Fairness: Pending in Queue",
   "type": "graph",
   "description": "Number of requests currently pending in queues of the API Priority and Fairness system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flow_schema_priority_level:apiserver_flowcontrol_current_inqueue_requests:sum{apiserver=\"$apiserver\"}",
     "legendFormat": "{{flow_schema}}:{{priority_level}}"
    }
   ]
  },
  {
   "title": "Self-requests Rate by Resource and Verb",
   "type": "graph",
   "description": "Counter of apiserver self-requests broken out for each verb, API resource and subresource.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resource_verb:apiserver_selfrequest_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Requests Aborted Rate by Instance",
   "type": "graph",
   "description": "Number of requests which apiserver aborted possibly due to a timeout, for each group, version, verb, resource, subresource and scope",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resource_verb:apiserver_request_aborts_total:rate$period{apiserver=\"$apiserver\"}",
     "legendFormat": "{{resource}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Server Filter Duration - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, histogram_quantile(0.99, filter:apiserver_request_filter_duration_seconds_bucket:rate$period{apiserver=\"$apiserver\"}))",
     "legendFormat": "{{filter}}"
    }
   ]
  },
  {
   "title": "Rate of Events Sent to Watch Clients",
   "type": "graph",
   "description": "Number of events sent in watch clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, group_kind:apiserver_watch_events_total:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Watch Event Size per Second by Group and Kind ",
   "type": "graph",
   "description": "Watch event size distribution in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, group_kind:apiserver_watch_events_sizes_sum:rate$period{apiserver=\"$apiserver\"})",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Registered Watchers",
   "type": "graph",
   "description": "Number of currently registered watchers for a given resources",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, group_kind:apiserver_registered_watchers:sum{apiserver=\"$apiserver\"})",
     "legendFormat": "{{group}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of TLS Handshake Error",
   "type": "graph",
   "description": "Number of requests dropped with 'TLS handshake error from' error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster:apiserver_tls_handshake_errors_total:rate$period{apiserver=\"$apiserver\"}"
    }
   ]
  },
  {
   "title": "etcd Object Count",
   "type": "graph",
   "description": "Number of stored objects at the time of last check split by kind.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, max(etcd_object_counts) by (resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}