package encryption

import (
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	utilerrors "k8s.io/apimachinery/pkg/util/errors"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/apimachinery/pkg/util/wait"
	corev1client "k8s.io/client-go/kubernetes/typed/core/v1"
	"k8s.io/client-go/tools/cache"
	"k8s.io/client-go/util/workqueue"
	"k8s.io/klog"

	operatorv1 "github.com/openshift/api/operator/v1"
	"github.com/openshift/library-go/pkg/operator/events"
	operatorv1helpers "github.com/openshift/library-go/pkg/operator/v1helpers"
)

const podStateKey = "key"

// encryptionPodStateController compares the state generated by encryptionStateController
// with the current state in use by the API server.  It waits until all API servers have
// converged onto a stable revision before making any checks.  It then traces each key
// back to the containing secret and marks it as observed as a read or write key.  Each
// state has an accompanying timestamp.  This controller effectively observes transitions
// from "new" to "read" to "write."
type encryptionPodStateController struct {
	operatorClient operatorv1helpers.StaticPodOperatorClient

	queue         workqueue.RateLimitingInterface
	eventRecorder events.Recorder

	preRunCachesSynced []cache.InformerSynced

	encryptedGRs map[schema.GroupResource]bool

	targetNamespace          string
	encryptionSecretSelector metav1.ListOptions

	secretClient corev1client.SecretsGetter

	podClient corev1client.PodInterface
}

func newEncryptionPodStateController(
	targetNamespace string,
	operatorClient operatorv1helpers.StaticPodOperatorClient,
	kubeInformersForNamespaces operatorv1helpers.KubeInformersForNamespaces,
	secretClient corev1client.SecretsGetter,
	encryptionSecretSelector metav1.ListOptions,
	eventRecorder events.Recorder,
	encryptedGRs map[schema.GroupResource]bool,
	podClient corev1client.PodInterface,
) *encryptionPodStateController {
	c := &encryptionPodStateController{
		operatorClient: operatorClient,

		queue:         workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "EncryptionPodStateController"),
		eventRecorder: eventRecorder.WithComponentSuffix("encryption-pod-state-controller"),

		encryptedGRs:    encryptedGRs,
		targetNamespace: targetNamespace,

		encryptionSecretSelector: encryptionSecretSelector,
		secretClient:             secretClient,
		podClient:                podClient,
	}

	c.preRunCachesSynced = setUpAllEncryptionInformers(operatorClient, targetNamespace, kubeInformersForNamespaces, c.eventHandler())

	return c
}

func (c *encryptionPodStateController) sync() error {
	if ready, err := shouldRunEncryptionController(c.operatorClient); err != nil || !ready {
		return err // we will get re-kicked when the operator status updates
	}

	isProgressingReason, configError := c.observeReadAndWriteKeysFromPodState()
	isProgressing := len(isProgressingReason) > 0

	// update failing condition
	degraded := operatorv1.OperatorCondition{
		Type:   "EncryptionPodStateControllerDegraded",
		Status: operatorv1.ConditionFalse,
	}
	if configError != nil {
		degraded.Status = operatorv1.ConditionTrue
		degraded.Reason = "Error"
		degraded.Message = configError.Error()
	}

	// update progressing condition
	progressing := operatorv1.OperatorCondition{
		Type:   "EncryptionPodStateControllerProgressing",
		Status: operatorv1.ConditionFalse,
	}
	if isProgressing {
		progressing.Status = operatorv1.ConditionTrue
		progressing.Reason = isProgressingReason
		progressing.Message = "" // TODO do we need something here?
	}

	if _, _, updateError := operatorv1helpers.UpdateStaticPodStatus(c.operatorClient,
		operatorv1helpers.UpdateStaticPodConditionFn(degraded),
		operatorv1helpers.UpdateStaticPodConditionFn(progressing),
	); updateError != nil {
		return updateError
	}

	if isProgressing && configError == nil {
		c.queue.AddAfter(podStateKey, 2*time.Minute)
	}

	return configError
}

func (c *encryptionPodStateController) observeReadAndWriteKeysFromPodState() (string, error) {
	// we need a stable view of the world
	encryptionConfig, encryptionState, isProgressingReason, err := getEncryptionConfigAndState(
		c.podClient, c.secretClient, c.targetNamespace, c.encryptionSecretSelector, c.encryptedGRs)
	if len(isProgressingReason) > 0 || err != nil {
		return isProgressingReason, err
	}

	// now we can attempt to annotate based on current pod state
	var errs []error
	var missingRead, missingWrite bool
	for gr, grActualKeys := range getGRsActualKeys(encryptionConfig) {
		keyToSecret := encryptionState[gr].keyToSecret

		for _, readKey := range grActualKeys.readKeys {
			readSecret, ok := keyToSecret[readKey]
			if !ok {
				klog.V(4).Infof("failed to find read secret for key %s in group=%s resource=%s", readKey.Name, groupToHumanReadable(gr), gr.Resource)
				missingRead = true
				continue
			}
			errs = append(errs, setTimestampAnnotationIfNotSet(c.secretClient, c.eventRecorder, readSecret, encryptionSecretReadTimestamp))
		}

		if !grActualKeys.hasWriteKey() {
			continue
		}

		writeSecret, ok := keyToSecret[grActualKeys.writeKey]
		if !ok {
			klog.V(4).Infof("failed to find write secret for key %s in group=%s resource=%s", grActualKeys.writeKey.Name, groupToHumanReadable(gr), gr.Resource)
			missingWrite = true
			continue
		}
		errs = append(errs, setTimestampAnnotationIfNotSet(c.secretClient, c.eventRecorder, writeSecret, encryptionSecretWriteTimestamp))
	}

	switch {
	case missingRead && missingWrite:
		isProgressingReason = "IncompleteReadAndWriteKeyToSecretMapping"
	case missingRead:
		isProgressingReason = "IncompleteReadKeyToSecretMapping"
	case missingWrite:
		isProgressingReason = "IncompleteWriteKeyToSecretMapping"
	}

	return isProgressingReason, utilerrors.NewAggregate(errs)
}

func (c *encryptionPodStateController) run(stopCh <-chan struct{}) {
	defer utilruntime.HandleCrash()
	defer c.queue.ShutDown()

	klog.Infof("Starting EncryptionPodStateController")
	defer klog.Infof("Shutting down EncryptionPodStateController")
	if !cache.WaitForCacheSync(stopCh, c.preRunCachesSynced...) {
		utilruntime.HandleError(fmt.Errorf("caches did not sync"))
		return
	}

	// only start one worker
	go wait.Until(c.runWorker, time.Second, stopCh)

	<-stopCh
}

func (c *encryptionPodStateController) runWorker() {
	for c.processNextWorkItem() {
	}
}

func (c *encryptionPodStateController) processNextWorkItem() bool {
	dsKey, quit := c.queue.Get()
	if quit {
		return false
	}
	defer c.queue.Done(dsKey)

	err := c.sync()
	if err == nil {
		c.queue.Forget(dsKey)
		return true
	}

	utilruntime.HandleError(fmt.Errorf("%v failed with: %v", dsKey, err))
	c.queue.AddRateLimited(dsKey)

	return true
}

func (c *encryptionPodStateController) eventHandler() cache.ResourceEventHandler {
	return cache.ResourceEventHandlerFuncs{
		AddFunc:    func(obj interface{}) { c.queue.Add(podStateKey) },
		UpdateFunc: func(old, new interface{}) { c.queue.Add(podStateKey) },
		DeleteFunc: func(obj interface{}) { c.queue.Add(podStateKey) },
	}
}
