apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kube-controller-manager
  namespace: {{ .Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-controller-manager
      tier: control-plane
