apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-apiserver
  namespace: {{ .Namespace }}
  labels:
    tier: "control-plane"
    k8s-app: "kube-apiserver"
    openshift.io/control-plane: "true"
    openshift.io/component: "api"
  annotations:
    openshift.io/run-level: "0"
spec:
  selector:
    matchLabels:
      tier: "control-plane"
      k8s-app: "kube-apiserver"
      openshift.io/control-plane: "true"
      openshift.io/component: "api"
  template:
    metadata:
      labels:
        tier: "control-plane"
        k8s-app: "kube-apiserver"
        openshift.io/control-plane: "true"
        openshift.io/component: "api"
    spec:
      securityContext:
        supplementalGroups: [65534]
      containers:
      - name: kube-apiserver
        image: {{ .Image }}
        imagePullPolicy: {{ .ImagePullPolicy }}
        command: ["/usr/bin/flock", "--exclusive", "--timeout=60", "/var/lock/api-server.lock", "-c"]
        args:
        - exec hypershift openshift-kube-apiserver --config=/etc/kubernetes/config/{{ .ConfigFileName }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /var/lock
          name: var-lock
          readOnly: false
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /etc/kubernetes/secrets
          name: secrets
          readOnly: true
        - mountPath: /etc/kubernetes/cloud
          name: etc-kubernetes-cloud
          readOnly: true
        - mountPath: /etc/kubernetes/config
          name: config
          readOnly: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - hostPath:
          path: /var/run/kubernetes/lock
        name: var-lock
      - hostPath:
          path: {{ .SecretsHostPath }}
        name: secrets
      - hostPath:
          path: {{ .CloudProviderHostPath }}
        name: etc-kubernetes-cloud
      - hostPath:
          path: {{ .ConfigHostPath }}
        name: config
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs-host
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate