apiVersion: v1
kind: Pod
metadata:
  namespace: openshift-kube-apiserver
  name: openshift-kube-apiserver
  labels:
    app: openshift-kube-apiserver
    apiserver: "true"
    revision: "REVISION"
spec:
  containers:
  - name: openshift-kube-apiserver
    image: ${IMAGE}
    imagePullPolicy: IfNotPresent
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["/bin/bash", "-c"]
    args:
      - |
        flock /etc/kubernetes/static-pod-sync hypershift openshift-kube-apiserver --config=/etc/kubernetes/static-pod-resources/configmaps/config/config.yaml &
        child=$!
        trap 'kill -TERM $child' TERM INT
        while ! -f /etc/kubernetes/static-pod-sync/shutdown; do sleep 1; done
        sleep 10 # wait for readiness probe to detect shutdown and to give endpoints time to propagate
        kill -TERM "$child" 2>/dev/null
        wait $child
    resources:
      requests:
        memory: 1Gi
    ports:
    - containerPort: 6443
    volumeMounts:
    - mountPath: /etc/kubernetes/static-pod-resources
      name: resource-dir
    - mountPath: /etc/kubernetes/static-pod-sync
      name: sync-dir
    livenessProbe:
      httpGet:
        scheme: HTTPS
        port: 6443
        path: healthz
      initialDelaySeconds: 45
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        scheme: HTTPS
        port: 6443
        path: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 10
  - name: readiness
    image: ${IMAGE}
    imagePullPolicy: IfNotPresent
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["tail -f /dev/null"]
    volumeMounts:
      - mountPath: /etc/kubernetes/static-pod-sync
        name: sync-dir
    readinessProbe:
      exec:
        command:
          - ! test -f /etc/kubernetes/static-pod-sync/shutdown
      initialDelaySeconds: 5
      periodSeconds: 5
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: "Exists"
  volumes:
  - hostPath:
      path: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-REVISION
    name: resource-dir
  - hostPath:
      path: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-sync
    name: sync-dir