apiVersion: v1
kind: Pod
metadata:
  namespace: openshift-kube-apiserver
  name: openshift-kube-apiserver
  labels:
    app: openshift-kube-apiserver
    deployment-id: "DEPLOYMENT_ID"
    apiserver: "true"
spec:
  containers:
  - name: apiserver
    image: ${IMAGE}
    imagePullPolicy: IfNotPresent
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["hypershift", "openshift-kube-apiserver"]
    args:
    - "--config=/etc/kubernetes/static-pod-resources/configmaps/deployment-kube-apiserver-config/config.yaml"
    ports:
    - containerPort: 6443
    volumeMounts:
    - mountPath: /etc/kubernetes/static-pod-resources
      name: resource-dir
    livenessProbe:
      httpGet:
        scheme: HTTPS
        port: 6443
        path: healthz
      initialDelaySeconds: 45
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        scheme: HTTPS
        port: 6443
        path: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 10
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-DEPLOYMENT_ID
    name: resource-dir
