apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  name: openshift-kube-apiserver
  labels:
    openshift.io/run-level: "0"
    openshift.io/cluster-monitoring: "true"
