# this matches what the installer uses to create the admin.kubeconfig.  We must always honor this as a client or the admin.kubeconfig will become invalid
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-kubeconfig-client-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    {{ .Assets | load "admin-kubeconfig-ca-bundle.crt" | indent 4 }}

