apiVersion: v1
kind: Secret
metadata:
  name: kube-control-plane-signer
  namespace: openshift-kube-apiserver-operator
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kube-control-plane-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kube-control-plane-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kube-control-plane-signer.crt" | issuer }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "kube-control-plane-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kube-control-plane-signer.key" | base64 }}
