apiVersion: v1
kind: Secret
metadata:
  name: localhost-serving-signer
  namespace: openshift-kube-apiserver-operator
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kube-apiserver-localhost-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kube-apiserver-localhost-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kube-apiserver-localhost-signer.crt" | issuer }}
    "openshift.io/owning-component": "kube-apiserver"
    "openshift.io/description": "Signer used by the kube-apiserver to create serving certificates for the kube-apiserver via localhost."
    "certificates.openshift.io/auto-regenerate-after-offline-expiry": "https://github.com/openshift/cluster-kube-apiserver-operator/pull/1631,'[Conformance][sig-api-machinery][Feature:APIServer] local kubeconfig \"localhost.kubeconfig\" should be present on all masters and work [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel/minimal]'"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Assets | load "kube-apiserver-localhost-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kube-apiserver-localhost-signer.key" | base64 }}
