apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-to-kubelet-signer
  namespace: openshift-kube-apiserver-operator
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | issuer }}
    "openshift.io/owning-component": "kube-apiserver"
    "openshift.io/description": "Signer for the kube-apiserver-to-kubelet-client so kubelets can recognize the kube-apiserver."
    "certificates.openshift.io/auto-regenerate-after-offline-expiry": "https://github.com/openshift/cluster-kube-apiserver-operator/pull/1631,'[sig-cli] Kubectl logs logs should be able to retrieve and filter logs  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]'"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Assets | load "kube-apiserver-to-kubelet-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kube-apiserver-to-kubelet-signer.key" | base64 }}
