apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-05-26T14:21:03Z"
  generation: 1
  name: kube-apiserver
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: adc1a305-3e98-4665-990d-a61c50b23b84
  resourceVersion: "753251"
  uid: 865b1d2a-b4e5-40f0-8cf4-8c124fcf0cdb
spec: {}
status:
  conditions:
  - lastTransitionTime: "2025-05-26T14:32:47Z"
    message: 'NodeControllerDegraded: All master nodes are ready'
    reason: AsExpected
    status: "False"
    type: Degraded
  - lastTransitionTime: "2025-05-28T14:16:41Z"
    message: 'NodeInstallerProgressing: 3 nodes are at revision 28'
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-05-26T14:30:17Z"
    message: 'StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 28'
    reason: AsExpected
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-26T14:24:39Z"
    message: 'KubeletMinorVersionUpgradeable: Kubelet and API server minor versions
      are synced.'
    reason: AsExpected
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2025-05-27T10:42:29Z"
    message: |-
      PodSecurityCustomerEvaluationConditionsDetected: Violations detected in namespaces: [ibihim-test-user-based-scc]
      PodSecurityInconclusiveEvaluationConditionsDetected: Could not evaluate violations for namespaces: [kube-node-lease openshift openshift-apiserver-operator openshift-cloud-credential-operator openshift-cloud-network-config-controller openshift-cluster-olm-operator openshift-cluster-samples-operator openshift-cluster-storage-operator openshift-config-managed openshift-config-operator openshift-console openshift-console-operator openshift-console-user-settings openshift-controller-manager openshift-controller-manager-operator openshift-dns-operator openshift-host-network openshift-ingress-canary openshift-ingress-operator openshift-kube-controller-manager-operator openshift-kube-storage-version-migrator openshift-kube-storage-version-migrator-operator openshift-network-console openshift-network-diagnostics openshift-node openshift-route-controller-manager openshift-service-ca openshift-service-ca-operator openshift-user-workload-monitoring]
    reason: PodSecurityCustomer_PSViolationsDetected::PodSecurityInconclusive_PSViolationDecisionInconclusive
    status: "True"
    type: EvaluationConditionsDetected
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: kubeapiservers
  - group: apiextensions.k8s.io
    name: ""
    resource: customresourcedefinitions
  - group: security.openshift.io
    name: ""
    resource: securitycontextconstraints
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-kube-apiserver-operator
    resource: namespaces
  - group: ""
    name: openshift-kube-apiserver
    resource: namespaces
  - group: admissionregistration.k8s.io
    name: ""
    resource: mutatingwebhookconfigurations
  - group: admissionregistration.k8s.io
    name: ""
    resource: validatingwebhookconfigurations
  - group: controlplane.operator.openshift.io
    name: ""
    namespace: openshift-kube-apiserver
    resource: podnetworkconnectivitychecks
  - group: apiserver.openshift.io
    name: ""
    resource: apirequestcounts
  - group: config.openshift.io
    name: cluster
    resource: nodes
  versions:
  - name: raw-internal
    version: 4.19.0-rc.3
  - name: kube-apiserver
    version: 1.32.4
  - name: operator
    version: 4.19.0-rc.3
