//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openshift/cluster-kube-apiserver-operator/cmd/cluster-kube-apiserver-operator-tests-ext/adapter"
)

// findRepoRoot walks up directories to find go.mod
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod in any parent directory")
		}
		dir = parent
	}
}

func main() {
	// Find repository root by looking for go.mod
	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to find repository root: %v\n", err)
		os.Exit(1)
	}

	// Set TEST_ROOT_DIR to repository root for discovery
	os.Setenv("TEST_ROOT_DIR", repoRoot)

	// Auto-discover all tests from test/e2e* directories
	configs, err := adapter.AutoDiscoverAllGoTests([]string{"Serial"}, nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to discover tests: %v\n", err)
		os.Exit(1)
	}

	if len(configs) == 0 {
		fmt.Fprintf(os.Stderr, "Warning: No tests discovered\n")
	}

	// Generate standard_go_tests.go file in the same directory as this script
	// This script is always in the adapter package directory
	scriptDir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to get script directory: %v\n", err)
		os.Exit(1)
	}

	// If running with "go run", find the actual source directory
	cwd, _ := os.Getwd()
	if filepath.Base(scriptDir) != "adapter" {
		scriptDir = cwd
	}

	outputPath := filepath.Join(scriptDir, "standard_go_tests.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by generate-test-metadata. DO NOT EDIT.
// To regenerate: make update

package adapter

import (
	"fmt"

	g "github.com/onsi/ginkgo/v2"
	extensiontests "github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests"
)

// Pre-discovered test metadata - embedded in binary at build time.
// To regenerate: developers run discovery locally and update this list.
var standardGoTestMetadata = []GoTestConfig{
`)

	for _, config := range configs {
		sb.WriteString(fmt.Sprintf("\t// %s\n", config.TestFile))

		// Format tags array
		var tagsStr string
		if len(config.Tags) == 0 {
			tagsStr = "[]string{}"
		} else {
			tagList := make([]string, len(config.Tags))
			for i, tag := range config.Tags {
				tagList[i] = fmt.Sprintf("%q", tag)
			}
			tagsStr = fmt.Sprintf("[]string{%s}", strings.Join(tagList, ", "))
		}

		// Include timeout if present
		if config.Timeout != "" {
			sb.WriteString(fmt.Sprintf("\t{TestFile: %q, TestPattern: %q, Tags: %s, Timeout: %q},\n",
				config.TestFile, config.TestPattern, tagsStr, config.Timeout))
		} else {
			sb.WriteString(fmt.Sprintf("\t{TestFile: %q, TestPattern: %q, Tags: %s},\n",
				config.TestFile, config.TestPattern, tagsStr))
		}
	}

	sb.WriteString(`}

// GetStandardGoTestSpecs returns ExtensionTestSpecs for standard Go tests
// This function is called by main.go to register the tests with OTE
func GetStandardGoTestSpecs() extensiontests.ExtensionTestSpecs {
	return BuildExtensionTestSpecsFromGoTestMetadata(standardGoTestMetadata)
}

// Register standard Go tests with Ginkgo for nice "Running Suite" output
// This var _ = pattern runs at package init time
var _ = g.Describe("[sig-api-machinery] kube-apiserver operator Standard Go Tests", func() {
	for _, config := range standardGoTestMetadata {
		config := config // capture loop variable

		testName := config.TestFile
		if config.TestPattern != "" {
			testName = fmt.Sprintf("%s:%s", config.TestFile, config.TestPattern)
		}

		// Run the test using RunGoTestFile
		// RunGoTestFile will add tags to the test name, so don't add them here
		RunGoTestFile(testName, config)
	}
})
`)

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d tests\n", outputPath, len(configs))
}
