//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openshift/cluster-kube-apiserver-operator/cmd/cluster-kube-apiserver-operator-tests-ext/adapter"
)

// findRepoRoot walks up directories to find go.mod
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod in any parent directory")
		}
		dir = parent
	}
}

func main() {
	// Find repository root by looking for go.mod
	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to find repository root: %v\n", err)
		os.Exit(1)
	}

	// Set TEST_ROOT_DIR to repository root for discovery
	os.Setenv("TEST_ROOT_DIR", repoRoot)

	// Auto-discover all tests from test/e2e* directories
	configs, err := adapter.AutoDiscoverAllGoTests([]string{"Serial"}, nil)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to discover tests: %v\n", err)
		os.Exit(1)
	}

	if len(configs) == 0 {
		fmt.Fprintf(os.Stderr, "Warning: No tests discovered\n")
	}

	// Generate standard_go_tests.go file in the same directory as this script
	// This script is always in the adapter package directory
	scriptDir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to get script directory: %v\n", err)
		os.Exit(1)
	}

	// If running with "go run", find the actual source directory
	cwd, _ := os.Getwd()
	if filepath.Base(scriptDir) != "adapter" {
		scriptDir = cwd
	}

	outputPath := filepath.Join(scriptDir, "standard_go_tests.go")

	var sb strings.Builder
	sb.WriteString(`// Code generated by generate-test-metadata. DO NOT EDIT.
// To regenerate: make update

package adapter

import (
	extensiontests "github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests"
)

// Pre-discovered test metadata - embedded in binary at build time.
// To regenerate: developers run discovery locally and update this list.
var standardGoTestMetadata = []GoTestConfig{
`)

	for _, config := range configs {
		sb.WriteString(fmt.Sprintf("\t// %s\n", config.TestFile))
		sb.WriteString(fmt.Sprintf("\t{TestFile: %q, TestPattern: %q, Tags: []string{\"Serial\"}},\n",
			config.TestFile, config.TestPattern))
	}

	sb.WriteString(`}

// GetStandardGoTestSpecs returns ExtensionTestSpecs for standard Go tests
// This function is called by main.go to register the tests with OTE
func GetStandardGoTestSpecs() extensiontests.ExtensionTestSpecs {
	return BuildExtensionTestSpecsFromGoTestMetadata(standardGoTestMetadata)
}
`)

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d tests\n", outputPath, len(configs))
}
